package com.example.ui.theme

import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF003D9B)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFF0052CC)
val onPrimaryContainerLight = Color(0xFFC4D2FF)
val secondaryLight = Color(0xFF00687B)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFF50DCFF)
val onSecondaryContainerLight = Color(0xFF005F71)
val tertiaryLight = Color(0xFF004E32)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFF006844)
val onTertiaryContainerLight = Color(0xFF72E9AF)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF93000A)
val backgroundLight = Color(0xFFF8F9FB)
val onBackgroundLight = Color(0xFF191C1E)
val surfaceLight = Color(0xFFF8F9FB)
val onSurfaceLight = Color(0xFF191C1E)
val surfaceVariantLight = Color(0xFFE1E2E4)
val onSurfaceVariantLight = Color(0xFF434654)
val outlineLight = Color(0xFF737685)
val outlineVariantLight = Color(0xFFC3C6D6)

// Dark themes mapping (we'll just use a slightly refined version but mostly stick to what was requested, or just use identical/adjusted values since dark mode specific isn't provided).
val primaryDark = Color(0xFFB2C5FF)
val onPrimaryDark = Color(0xFF001848)
val primaryContainerDark = Color(0xFF0040A2)
val onPrimaryContainerDark = Color(0xFFDAE2FF)
val secondaryDark = Color(0xFFAFECFF)
val onSecondaryDark = Color(0xFF001F27)
val secondaryContainerDark = Color(0xFF004E5D)
val onSecondaryContainerDark = Color(0xFF48D7F9)
val tertiaryDark = Color(0xFF82F9BE)
val onTertiaryDark = Color(0xFF002113)
val tertiaryContainerDark = Color(0xFF005235)
val onTertiaryContainerDark = Color(0xFF65DCA4)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF111416)
val onBackgroundDark = Color(0xFFE2E2E5)
val surfaceDark = Color(0xFF111416)
val onSurfaceDark = Color(0xFFE2E2E5)
val surfaceVariantDark = Color(0xFF434654)
val onSurfaceVariantDark = Color(0xFFC3C6D6)
val outlineDark = Color(0xFF8D90A0)
val outlineVariantDark = Color(0xFF434654)

